language: python
python:
  - "3.5" # current version
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS lmnad_db;'
  - python -m pip install --upgrade pip
install:
  - pip install -r requirements.txt
before_script:

script:
  - python manage.py test
