# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-30 10:17
from __future__ import unicode_literals

from django.db import migrations, models
import geoposition.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', geoposition.fields.GeopositionField(max_length=42, verbose_name='\u041a\u043e\u043e\u0440\u0434\u0438\u043d\u0430\u0442\u044b')),
                ('types', models.TextField(help_text='\u041c\u043e\u0436\u0435\u0442 \u0431\u044b\u0442\u044c \u043d\u0435\u0441\u043a\u043e\u043b\u044c\u043a\u043e \u0442\u0438\u043f\u043e\u0432', verbose_name='\u0422\u0438\u043f')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u0438 \u0432\u0440\u0435\u043c\u044f \u043d\u0430\u0431\u043b\u044e\u0434\u0435\u043d\u0438\u044f')),
                ('date_start', models.DateTimeField(blank=True, help_text='\u0415\u0441\u043b\u0438 \u0435\u0441\u0442\u044c', null=True, verbose_name='\u0414\u0430\u0442\u0430 \u0438 \u0432\u0440\u0435\u043c\u044f \u043d\u0430\u0447\u0430\u043b\u0430 \u043d\u0430\u0431\u043b\u044e\u0434\u0435\u043d\u0438\u0439')),
                ('date_stop', models.DateTimeField(blank=True, help_text='\u0415\u0441\u043b\u0438 \u0435\u0441\u0442\u044c', null=True, verbose_name='\u0414\u0430\u0442\u0430 \u0438 \u0432\u0440\u0435\u043c\u044f \u043a\u043e\u043d\u0446\u0430 \u043d\u0430\u0431\u043b\u044e\u0434\u0435\u043d\u0438\u0439')),
                ('image', models.ImageField(blank=True, upload_to='uploads/igwatlas/images', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435')),
                ('page', models.PositiveIntegerField(blank=True, null=True, verbose_name='\u0421\u0442\u0440\u0430\u043d\u0438\u0446\u0430 \u0438\u0437 \u0438\u0441\u0442\u043e\u0447\u043d\u0438\u043a\u0430')),
                ('data', models.FileField(blank=True, help_text='\u0415\u0441\u043b\u0438 \u0435\u0441\u0442\u044c', null=True, upload_to='uploads/igwatlas/data', verbose_name='\u041e\u0446\u0438\u0444\u0440\u043e\u0432\u0430\u043d\u043d\u044b\u0435 \u0434\u0430\u043d\u043d\u044b\u0435')),
            ],
            options={
                'verbose_name': '\u041d\u0430\u0431\u043b\u044e\u0434\u0435\u043d\u0438\u0435',
                'verbose_name_plural': '\u041d\u0430\u0431\u043b\u044e\u0434\u0435\u043d\u0438\u044f',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_short', models.CharField(max_length=255, verbose_name='\u041a\u0440\u0430\u0442\u043a\u043e\u0435 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('source', models.TextField(verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('file', models.FileField(blank=True, help_text='\u0415\u0441\u043b\u0438 \u0435\u0441\u0442\u044c', null=True, upload_to='uploads/igwatlas/sources', verbose_name='\u0424\u0430\u0439\u043b \u0434\u043b\u044f \u0438\u0441\u0442\u043e\u0447\u043d\u0438\u043a\u0430')),
                ('link', models.CharField(blank=True, help_text='\u0415\u0441\u043b\u0438 \u0435\u0441\u0442\u044c', max_length=200, null=True, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430')),
            ],
            options={
                'verbose_name': '\u0418\u0441\u0442\u043e\u0447\u043d\u0438\u043a',
                'verbose_name_plural': '\u0418\u0441\u0442\u043e\u0447\u043d\u0438\u043a\u0438',
            },
        ),
        migrations.AddField(
            model_name='record',
            name='source',
            field=models.ManyToManyField(to='igwatlas.Source', verbose_name='\u0418\u0441\u0442\u043e\u0447\u043d\u0438\u043a'),
        ),
    ]
