# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-17 07:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('igwatlas', '0002_auto_20170517_0924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='file',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='source',
            old_name='file',
            new_name='files',
        ),
    ]
