# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-17 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igwatlas', '0003_auto_20170517_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='name',
        ),
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/igwatlas/sources', verbose_name='\u0424\u0430\u0439\u043b'),
        ),
        migrations.AddField(
            model_name='file',
            name='path',
            field=models.FilePathField(blank=True, null=True, path='uploads/igwatlas/sources', verbose_name='\u041f\u0443\u0442\u044c \u043a \u0444\u0430\u0439\u043b\u0443'),
        ),
    ]
