# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-07-08 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igwatlas', '0007_auto_20170604_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.PositiveIntegerField(choices=[(0, '\u0422\u0435\u043a\u0441\u0442 \u043e \u0442\u0438\u043f\u0435: \u043a\u0430\u0440\u0442\u0430'), (1, '\u0422\u0435\u043a\u0441\u0442 \u043e \u0442\u0438\u043f\u0435: \u0433\u0440\u0430\u0444\u0438\u043a'), (2, '\u0422\u0435\u043a\u0441\u0442 \u043e \u0442\u0438\u043f\u0435: \u0441\u043f\u0443\u0442\u043d\u0438\u043a'), (3, '\u0422\u0435\u043a\u0441\u0442 \u043e \u0442\u0438\u043f\u0435: \u0437\u0430\u043f\u0438\u0441\u044c'), (4, '\u0422\u0435\u043a\u0441\u0442 \u043e \u0442\u0438\u043f\u0435: \u0442\u0430\u0431\u043b\u0438\u0446\u0430'), (5, '\u0422\u0435\u043a\u0441\u0442 \u043e \u043f\u0440\u043e\u0435\u043a\u0442\u0435')], default=0, verbose_name='\u0422\u0438\u043f \u0434\u0430\u043d\u043d\u044b\u0445, \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b')),
                ('title', models.CharField(max_length=200, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('text', models.TextField(verbose_name='\u0422\u0435\u043a\u0441\u0442')),
            ],
            options={
                'verbose_name': '\u0414\u0430\u043d\u043d\u044b\u0435 \u0434\u043b\u044f \u0441\u0442\u0440\u0430\u043d\u0438\u0446',
                'verbose_name_plural': '\u0414\u0430\u043d\u043d\u044b\u0435 \u0434\u043b\u044f \u0441\u0442\u0440\u0430\u043d\u0438\u0446',
            },
        ),
    ]
