# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-07-08 10:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('igwatlas', '0008_pagedata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagedata',
            old_name='types',
            new_name='type',
        ),
    ]
