# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-07-08 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igwatlas', '0009_auto_20170708_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagedata',
            name='type',
            field=models.PositiveIntegerField(choices=[(0, '\u0422\u0435\u043a\u0441\u0442 \u043e \u0442\u0438\u043f\u0435: \u043a\u0430\u0440\u0442\u0430'), (1, '\u0422\u0435\u043a\u0441\u0442 \u043e \u0442\u0438\u043f\u0435: \u0433\u0440\u0430\u0444\u0438\u043a'), (2, '\u0422\u0435\u043a\u0441\u0442 \u043e \u0442\u0438\u043f\u0435: \u0441\u043f\u0443\u0442\u043d\u0438\u043a'), (3, '\u0422\u0435\u043a\u0441\u0442 \u043e \u0442\u0438\u043f\u0435: \u0437\u0430\u043f\u0438\u0441\u044c'), (4, '\u0422\u0435\u043a\u0441\u0442 \u043e \u0442\u0438\u043f\u0435: \u0442\u0430\u0431\u043b\u0438\u0446\u0430'), (5, '\u0422\u0435\u043a\u0441\u0442 \u043e \u043f\u0440\u043e\u0435\u043a\u0442\u0435')], default=0, unique=True, verbose_name='\u0422\u0438\u043f \u0434\u0430\u043d\u043d\u044b\u0445, \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b'),
        ),
    ]
