# Generated by Django 2.0.10 on 2019-02-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igwatlas', '0011_auto_20170715_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, unique=True, verbose_name='Название типа записи')),
                ('value', models.PositiveIntegerField(default=0, unique=True, verbose_name='Цифровое значение для типа')),
            ],
        ),
        migrations.AlterField(
            model_name='record',
            name='types',
            field=models.TextField(blank=True, choices=[(0, 'Карта'), (1, 'График'), (2, 'Спутниковый снимок'), (3, 'Запись'), (4, 'Таблица')], help_text='Поддерживается несколько типов', null=True, verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='record',
            name='new_types',
            field=models.ManyToManyField(help_text='Поддерживается несколько типов', to='igwatlas.RecordType', verbose_name='Тип'),
        ),
    ]
