# Generated by Django 2.0.10 on 2020-05-29 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('igwatlas', '0012_auto_20190215_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaveData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveIntegerField(choices=[(0, 'Длинные волны'), (1, 'Внутренний бор'), (2, 'Короткопериодные волны')], default=2, unique=True, verbose_name='Тип ВВ')),
                ('mode', models.PositiveIntegerField(default=1, verbose_name='Мода ВВ')),
                ('amplitude', models.FloatField(verbose_name='Амплитуда ВВ в метрах')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='igwatlas.Record', verbose_name='Запись для анализа')),
            ],
            options={
                'verbose_name': 'Параметры',
                'verbose_name_plural': 'Параметры',
            },
        ),
    ]
