# Generated by Django 2.0.10 on 2019-03-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igwatlas', '0012_auto_20190215_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='is_verified',
            field=models.BooleanField(default=True, help_text='Поставьте галочку, если запись проверена', verbose_name='Проверено'),
        ),
    ]
