# Generated by Django 2.0.10 on 2020-06-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igwatlas', '0013_wavedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='wavedata',
            name='period',
            field=models.FloatField(default=0, verbose_name='Период ВВ в часах'),
            preserve_default=False,
        ),
    ]
