# Generated by Django 2.0.10 on 2019-03-16 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lmnad', '0034_auto_20181019_1354'),
        ('igwatlas', '0014_auto_20190316_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='lmnad.Account', verbose_name='Пользователь'),
        ),
    ]
