# Generated by Django 2.0.10 on 2020-06-18 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igwatlas', '0015_auto_20200609_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='wavedata',
            name='polarity',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'Отрицательная'), (1, 'Положительная'), (2, 'Выпуклая'), (3, 'Вогнутая')], null=True, unique=True, verbose_name='Полярность ВВ'),
        ),
    ]
