# Generated by Django 2.0.10 on 2019-10-29 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igwatlas', '0016_auto_20190323_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='data',
        ),
        migrations.RemoveField(
            model_name='record',
            name='types',
        ),
        migrations.AlterField(
            model_name='record',
            name='image',
            field=models.ImageField(upload_to='uploads/igwatlas/images', verbose_name='Изображение'),
        ),
    ]
