# Generated by Django 2.0.12 on 2020-06-22 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('igwatlas', '0017_auto_20191029_2307'),
        ('igwatlas', '0016_wavedata_polarity'),
    ]

    operations = [
    ]
