# Generated by Django 2.0.12 on 2020-06-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igwatlas', '0018_merge_20200622_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wavedata',
            name='polarity',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'Negative'), (1, 'Positive'), (2, 'Convex'), (3, 'Concave')], null=True, unique=True, verbose_name='Полярность ВВ'),
        ),
        migrations.AlterField(
            model_name='wavedata',
            name='type',
            field=models.PositiveIntegerField(choices=[(0, 'Long wave'), (1, 'Internal bore'), (2, 'Short period wave')], default=2, unique=True, verbose_name='Тип ВВ'),
        ),
    ]
