# Generated by Django 2.0.10 on 2020-06-25 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igwatlas', '0019_auto_20200624_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wavedata',
            name='polarity',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'Отрицательная'), (1, 'Положительная'), (2, 'Выпуклая'), (3, 'Вогнутая')], null=True, verbose_name='Полярность ВВ'),
        ),
        migrations.AlterField(
            model_name='wavedata',
            name='type',
            field=models.PositiveIntegerField(choices=[(0, 'Длинные волны'), (1, 'Внутренний бор'), (2, 'Короткопериодные волны')], default=2, verbose_name='Тип ВВ'),
        ),
    ]
