# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-06-14 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lmnad', '0025_auto_20180614_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=55, verbose_name='\u0418\u043c\u044f')),
                ('last_name', models.CharField(max_length=55, verbose_name='\u0424\u0430\u043c\u0438\u043b\u0438\u044f')),
                ('middle_name', models.CharField(blank=True, max_length=55, verbose_name='\u041e\u0442\u0447\u0435\u0441\u0442\u0432\u043e')),
                ('user', models.ForeignKey(blank=True, help_text='\u0415\u0441\u043b\u0438 \u0435\u0441\u0442\u044c \u0430\u043a\u043a\u0430\u0443\u043d\u0442', null=True, on_delete=django.db.models.deletion.CASCADE, to='lmnad.Account', verbose_name='\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c')),
            ],
            options={
                'verbose_name': '\u0410\u0432\u0442\u043e\u0440',
                'verbose_name_plural': '\u0410\u0432\u0442\u043e\u0440\u044b',
            },
        ),
        migrations.CreateModel(
            name='AuthorPublication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_by', models.PositiveIntegerField(default=0, help_text='\u041e\u0442 0 - 100', verbose_name='\u041f\u043e\u0440\u044f\u0434\u043e\u043a \u043e\u0442\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u044f')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.Author', verbose_name='\u0410\u0432\u0442\u043e\u0440')),
            ],
            options={
                'verbose_name': '\u0410\u0432\u0442\u043e\u0440',
                'verbose_name_plural': '\u0410\u0432\u0442\u043e\u0440\u044b',
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0436\u0443\u0440\u043d\u0430\u043b\u0430, \u043a\u043e\u043d\u0444\u0435\u0440\u0435\u043d\u0446\u0438\u0438')),
            ],
            options={
                'verbose_name': '\u0416\u0443\u0440\u043d\u0430\u043b',
                'verbose_name_plural': '\u0416\u0443\u0440\u043d\u0430\u043b\u044b',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('type', models.CharField(choices=[('Article', '\u0421\u0442\u0430\u0442\u044c\u044f')], default='Article', max_length=55, verbose_name='\u0422\u0438\u043f \u043f\u0443\u0431\u043b\u0438\u043a\u0430\u0446\u0438\u0438')),
                ('title', models.CharField(max_length=200, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('year', models.IntegerField(verbose_name='\u0413\u043e\u0434')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u0438 \u0432\u0440\u0435\u043c\u044f')),
                ('volume', models.CharField(blank=True, max_length=15, verbose_name='\u0422\u043e\u043c, \u043d\u043e\u043c\u0435\u0440')),
                ('pages', models.CharField(blank=True, max_length=15, verbose_name='\u0421\u0442\u0440\u0430\u043d\u0438\u0446\u044b')),
                ('number', models.PositiveIntegerField(blank=True, null=True, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0441\u0432\u0438\u0434\u0435\u0442\u0435\u043b\u044c\u0441\u0442\u0432\u0430')),
                ('link', models.CharField(blank=True, help_text='\u0415\u0441\u043b\u0438 \u0435\u0441\u0442\u044c', max_length=200, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430')),
                ('doi', models.CharField(blank=True, help_text='\u0415\u0441\u043b\u0438 \u0435\u0441\u0442\u044c', max_length=200, verbose_name='DOI')),
                ('is_rinc', models.BooleanField(default=False, help_text='\u041e\u0442\u043c\u0435\u0442\u044c\u0442\u0435 \u0433\u0430\u043b\u043e\u0447\u043a\u0443, \u0435\u0441\u043b\u0438 \u043f\u0443\u0431\u043b\u0438\u043a\u0430\u0446\u0438\u044f \u0432\u0445\u043e\u0434\u0438\u0442 \u0432 \u0420\u0418\u041d\u0426', verbose_name='\u0412\u0445\u043e\u0434\u0438\u0442 \u0432 \u0420\u0418\u041d\u0426')),
                ('is_wos', models.BooleanField(default=False, help_text='\u041e\u0442\u043c\u0435\u0442\u044c\u0442\u0435 \u0433\u0430\u043b\u043e\u0447\u043a\u0443, \u0435\u0441\u043b\u0438 \u043f\u0443\u0431\u043b\u0438\u043a\u0430\u0446\u0438\u044f \u0432\u0445\u043e\u0434\u0438\u0442 \u0432 Web of Science', verbose_name='\u0412\u0445\u043e\u0434\u0438\u0442 \u0432 WOS')),
                ('is_scopus', models.BooleanField(default=False, help_text='\u041e\u0442\u043c\u0435\u0442\u044c\u0442\u0435 \u0433\u0430\u043b\u043e\u0447\u043a\u0443, \u0435\u0441\u043b\u0438 \u043f\u0443\u0431\u043b\u0438\u043a\u0430\u0446\u0438\u044f \u0432\u0445\u043e\u0434\u0438\u0442 \u0432 Scopus', verbose_name='\u0412\u0445\u043e\u0434\u0438\u0442 \u0432 Scopus')),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/articles/', verbose_name='\u0424\u0430\u0439\u043b \u0441 \u0442\u0435\u043a\u0442\u043e\u043c \u0441\u0442\u0430\u0442\u044c\u0438')),
                ('is_can_download', models.BooleanField(default=False, help_text='\u041e\u0442\u043c\u0435\u0442\u044c\u0442\u0435 \u0433\u0430\u043b\u043e\u0447\u043a\u0443, \u0435\u0441\u043b\u0438 \u0444\u0430\u0439\u043b \u0434\u043e\u0441\u0442\u0443\u043f\u0435\u043d \u0434\u043b\u044f \u0441\u043a\u0430\u0447\u0438\u0432\u0430\u043d\u0438\u044f', verbose_name='\u041c\u043e\u0436\u043d\u043e \u0441\u043a\u0430\u0447\u0430\u0442\u044c')),
                ('is_show', models.BooleanField(default=True, help_text='\u041e\u0442\u043c\u0435\u0442\u044c\u0442\u0435 \u0433\u0430\u043b\u043e\u0447\u043a\u0443, \u0447\u0442\u043e\u0431\u044b \u043f\u0443\u0431\u043b\u0438\u043a\u0430\u0446\u0438\u044f \u0431\u044b\u043b\u0430 \u0434\u043e\u0441\u0442\u0443\u043f\u043d\u0430 \u043d\u0430 \u0441\u0430\u0439\u0442\u0435', verbose_name='\u041f\u043e\u043a\u0430\u0437\u044b\u0432\u0430\u0442\u044c \u043d\u0430 \u0441\u0430\u0439\u0442\u0435')),
                ('authors', models.ManyToManyField(through='publications.AuthorPublication', to='publications.Author', verbose_name='\u0410\u0432\u0442\u043e\u0440\u044b')),
                ('journal', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='publications.Journal', verbose_name='\u0416\u0443\u0440\u043d\u0430\u043b, \u043a\u043e\u043d\u0444\u0435\u0440\u0435\u043d\u0446\u0438\u044f')),
            ],
            options={
                'verbose_name': '\u041f\u0443\u0431\u043b\u0438\u043a\u0430\u0446\u0438\u044f',
                'verbose_name_plural': '\u041f\u0443\u0431\u043b\u0438\u043a\u0430\u0446\u0438\u0438',
            },
        ),
        migrations.AddField(
            model_name='authorpublication',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.Publication', verbose_name='\u041f\u0443\u0431\u043b\u0438\u043a\u0430\u0446\u0438\u044f'),
        ),
    ]
