# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-06-14 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='pages',
            field=models.CharField(blank=True, max_length=55, verbose_name='\u0421\u0442\u0440\u0430\u043d\u0438\u0446\u044b'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='volume',
            field=models.CharField(blank=True, max_length=55, verbose_name='\u0422\u043e\u043c, \u043d\u043e\u043c\u0435\u0440'),
        ),
    ]
