# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-06-18 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_auto_20180614_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='issue',
            field=models.CharField(blank=True, max_length=55, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0436\u0443\u0440\u043d\u0430\u043b\u0430'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='volume',
            field=models.CharField(blank=True, max_length=55, verbose_name='\u0422\u043e\u043c'),
        ),
    ]
