# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-06-21 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_auto_20180618_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='last_name_en',
            field=models.CharField(max_length=55, null=True, verbose_name='\u0424\u0430\u043c\u0438\u043b\u0438\u044f'),
        ),
        migrations.AddField(
            model_name='author',
            name='last_name_ru',
            field=models.CharField(max_length=55, null=True, verbose_name='\u0424\u0430\u043c\u0438\u043b\u0438\u044f'),
        ),
        migrations.AddField(
            model_name='author',
            name='middle_name_en',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='\u041e\u0442\u0447\u0435\u0441\u0442\u0432\u043e'),
        ),
        migrations.AddField(
            model_name='author',
            name='middle_name_ru',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='\u041e\u0442\u0447\u0435\u0441\u0442\u0432\u043e'),
        ),
        migrations.AddField(
            model_name='author',
            name='name_en',
            field=models.CharField(max_length=55, null=True, verbose_name='\u0418\u043c\u044f'),
        ),
        migrations.AddField(
            model_name='author',
            name='name_ru',
            field=models.CharField(max_length=55, null=True, verbose_name='\u0418\u043c\u044f'),
        ),
        migrations.AddField(
            model_name='journal',
            name='name_en',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0436\u0443\u0440\u043d\u0430\u043b\u0430, \u043a\u043e\u043d\u0444\u0435\u0440\u0435\u043d\u0446\u0438\u0438'),
        ),
        migrations.AddField(
            model_name='journal',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0436\u0443\u0440\u043d\u0430\u043b\u0430, \u043a\u043e\u043d\u0444\u0435\u0440\u0435\u043d\u0446\u0438\u0438'),
        ),
        migrations.AddField(
            model_name='publication',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435'),
        ),
        migrations.AddField(
            model_name='publication',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435'),
        ),
    ]
