# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-09-18 13:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0007_auto_20180918_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='user',
            field=models.ForeignKey(blank=True, help_text='\u0415\u0441\u043b\u0438 \u0435\u0441\u0442\u044c \u0430\u043a\u043a\u0430\u0443\u043d\u0442', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to='lmnad.Account', verbose_name='\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c'),
        ),
    ]
