# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-09-20 11:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0008_auto_20180918_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publications.Journal', verbose_name='\u0416\u0443\u0440\u043d\u0430\u043b, \u043a\u043e\u043d\u0444\u0435\u0440\u0435\u043d\u0446\u0438\u044f'),
        ),
    ]
