# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-09-20 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0009_auto_20180920_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='number',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0441\u0432\u0438\u0434\u0435\u0442\u0435\u043b\u044c\u0441\u0442\u0432\u0430'),
        ),
    ]
