# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-09-21 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0011_auto_20180920_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='language',
            field=models.CharField(choices=[('ru', '\u0420\u0443\u0441\u0441\u043a\u0438\u0439'), ('en', '\u0410\u043d\u0433\u043b\u0438\u0439\u043a\u0438\u0439')], default='ru', help_text='\u0418\u0441\u043f\u043e\u043b\u044c\u0437\u0443\u0435\u0442\u0441\u044f \u0434\u043b\u044f \u044d\u043a\u043f\u043e\u0440\u0442\u0430/\u0446\u0438\u0442\u0438\u0440\u043e\u0432\u0430\u043d\u0438\u044f \u043d\u0430 \u0441\u0430\u0439\u0442\u0435 \u0432 \u043d\u0435\u0437\u0430\u0432\u0438\u0441\u0438\u043c\u043e\u0441\u0442\u0438 \u043e\u0442 \u0432\u044b\u0431\u0440\u0430\u043d\u043d\u043e\u0433\u043e \u044f\u0437\u044b\u043a\u0430 \u043d\u0430 \u0441\u0430\u0439\u0442\u0435', max_length=10, verbose_name='\u041e\u0441\u043d\u043e\u0432\u043d\u043e\u0439 \u044f\u0437\u044b\u043a \u043f\u0443\u0431\u043b\u0438\u043a\u0430\u0446\u0438\u0438'),
        ),
    ]
