# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-09-29 03:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0012_auto_20180921_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('type', models.CharField(choices=[('international', '\u041c\u0435\u0436\u0434\u0443\u043d\u0430\u0440\u043e\u0434\u043d\u0430\u044f'), ('national', '\u0420\u043e\u0441\u0441\u0438\u0439\u0441\u043a\u0430\u044f')], default='national', max_length=25, verbose_name='\u041a\u043b\u0430\u0441\u0441\u0438\u0444\u0438\u043a\u0430\u0446\u0438\u044f')),
                ('organizer', models.CharField(blank=True, max_length=550, verbose_name='\u041e\u0440\u0433\u0430\u043d\u0438\u0437\u0430\u0442\u043e\u0440')),
                ('date_start', models.DateTimeField(blank=True, help_text='\u041d\u0430\u0447\u0430\u043b\u043e \u043a\u043e\u043d\u0444\u0435\u0440\u0435\u043d\u0446\u0438\u0438', null=True, verbose_name='\u0414\u0430\u0442\u0430 \u0438 \u0432\u0440\u0435\u043c\u044f')),
                ('date_stop', models.DateTimeField(blank=True, help_text='\u041a\u043e\u043d\u0435\u0446 \u043a\u043e\u043d\u0444\u0435\u0440\u0435\u043d\u0446\u0438\u0438', null=True, verbose_name='\u0414\u0430\u0442\u0430 \u0438 \u0432\u0440\u0435\u043c\u044f')),
                ('place', models.CharField(blank=True, help_text='\u041d\u0430\u043f\u0440\u0438\u043c\u0435\u0440: \u0421\u0442\u0440\u0430\u043d\u0430, \u0433\u043e\u0440\u043e\u0434 \u0438\u043b\u0438 \u0443\u043d\u0438\u0432\u0435\u0440\u0441\u0438\u0442\u0435\u0442', max_length=255, verbose_name='\u041c\u0435\u0441\u0442\u043e \u043f\u0440\u043e\u0432\u0435\u0434\u0435\u043d\u0438\u044f')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.Author', verbose_name='\u0414\u043e\u043a\u043b\u0430\u0434\u0447\u0438\u043a')),
            ],
            options={
                'verbose_name': '\u0423\u0447\u0430\u0441\u0442\u043d\u0438\u043a \u043a\u043e\u043d\u0444\u0435\u0440\u0435\u043d\u0446\u0438\u0438',
                'verbose_name_plural': '\u0423\u0447\u0430\u0441\u0442\u043d\u0438\u043a\u0438 \u043a\u043e\u043d\u0444\u0435\u0440\u0435\u043d\u0446\u0438\u0439',
            },
        ),
        migrations.AlterModelOptions(
            name='journal',
            options={'verbose_name': '\u0416\u0443\u0440\u043d\u0430\u043b/\u041a\u043e\u043d\u0444\u0435\u0440\u0435\u043d\u0446\u0438\u044f', 'verbose_name_plural': '\u0416\u0443\u0440\u043d\u0430\u043b\u044b/\u041a\u043e\u043d\u0444\u0435\u0440\u0435\u043d\u0446\u0438\u0438'},
        ),
        migrations.AlterField(
            model_name='publication',
            name='issue',
            field=models.CharField(blank=True, max_length=55, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0436\u0443\u0440\u043d\u0430\u043b\u0430/\u043a\u043e\u043d\u0444\u0435\u0440\u0435\u043d\u0446\u0438\u0438'),
        ),
        migrations.AddField(
            model_name='conference',
            name='publication',
            field=models.ForeignKey(help_text='\u041e\u0442\u0441\u044e\u0434\u0430 \u0431\u0435\u0440\u0451\u0442\u0441\u044f \u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0434\u043e\u043a\u043b\u0430\u0434\u0430 \u0438 \u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043a\u043e\u043d\u0444\u0435\u0440\u0435\u043d\u0446\u0438\u0438', on_delete=django.db.models.deletion.CASCADE, to='publications.Publication', verbose_name='\u041f\u0443\u0431\u043b\u0438\u043a\u0430\u0446\u0438\u044f'),
        ),
    ]
