# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-10-01 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0014_auto_20181001_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='form',
            field=models.CharField(choices=[('oral', '\u0423\u0441\u0442\u043d\u0430\u044f'), ('poster', '\u041f\u043e\u0441\u0442\u0435\u0440')], default='oral', max_length=25, verbose_name='\u0424\u043e\u0440\u043c\u0430 \u0434\u043e\u043a\u043b\u0430\u0434\u0430'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='place',
            field=models.CharField(blank=True, help_text='\u041d\u0430\u043f\u0440\u0438\u043c\u0435\u0440: \u0421\u0442\u0440\u0430\u043d\u0430, \u0433\u043e\u0440\u043e\u0434, \u0443\u043d\u0438\u0432\u0435\u0440\u0441\u0438\u0442\u0435\u0442', max_length=255, verbose_name='\u041c\u0435\u0441\u0442\u043e \u043f\u0440\u043e\u0432\u0435\u0434\u0435\u043d\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='publication',
            field=models.OneToOneField(help_text='\u041e\u0442\u0441\u044e\u0434\u0430 \u0431\u0435\u0440\u0451\u0442\u0441\u044f \u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0434\u043e\u043a\u043b\u0430\u0434\u0430 \u0438 \u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043a\u043e\u043d\u0444\u0435\u0440\u0435\u043d\u0446\u0438\u0438: \u0441\u0442\u0430\u0442\u044c\u044f \u0432 \u0441\u0431\u043e\u0440\u043d\u0438\u043a\u0430\u0445 \u0442\u0440\u0443\u0434\u043e\u0432 \u043a\u043e\u043d\u0444\u0435\u0440\u0435\u043d\u0446\u0438\u0438 \u0438\u043b\u0438 \u0442\u0435\u0437\u0438\u0441\u044b \u043a\u043e\u043d\u0444\u0435\u0440\u0435\u043d\u0446\u0438\u0438', on_delete=django.db.models.deletion.CASCADE, related_name='conference', to='publications.Publication', verbose_name='\u041f\u0443\u0431\u043b\u0438\u043a\u0430\u0446\u0438\u044f'),
        ),
    ]
