# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-10-02 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0015_auto_20181001_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='date_start',
            field=models.DateTimeField(help_text='\u041d\u0430\u0447\u0430\u043b\u043e \u043a\u043e\u043d\u0444\u0435\u0440\u0435\u043d\u0446\u0438\u0438', verbose_name='\u0414\u0430\u0442\u0430 \u0438 \u0432\u0440\u0435\u043c\u044f, \u043d\u0430\u0447\u0430\u043b\u043e'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='date_stop',
            field=models.DateTimeField(help_text='\u041a\u043e\u043d\u0435\u0446 \u043a\u043e\u043d\u0444\u0435\u0440\u0435\u043d\u0446\u0438\u0438', verbose_name='\u0414\u0430\u0442\u0430 \u0438 \u0432\u0440\u0435\u043c\u044f, \u043a\u043e\u043d\u0435\u0446'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='place',
            field=models.CharField(help_text='\u041d\u0430\u043f\u0440\u0438\u043c\u0435\u0440: \u0421\u0442\u0440\u0430\u043d\u0430, \u0433\u043e\u0440\u043e\u0434, \u0443\u043d\u0438\u0432\u0435\u0440\u0441\u0438\u0442\u0435\u0442', max_length=255, verbose_name='\u041c\u0435\u0441\u0442\u043e \u043f\u0440\u043e\u0432\u0435\u0434\u0435\u043d\u0438\u044f'),
        ),
    ]
