# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-10-03 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0016_auto_20181002_1148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conference',
            options={'verbose_name': '\u0423\u0447\u0430\u0441\u0442\u0438\u0435 \u0432 \u043a\u043e\u043d\u0444\u0435\u0440\u0435\u043d\u0446\u0438\u0438', 'verbose_name_plural': '\u0423\u0447\u0430\u0441\u0442\u0438\u0435 \u0432 \u043a\u043e\u043d\u0444\u0435\u0440\u0435\u043d\u0446\u0438\u044f\u0445'},
        ),
        migrations.RemoveField(
            model_name='conference',
            name='date_start',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='date_stop',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='organizer',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='place',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='type',
        ),
        migrations.AddField(
            model_name='journal',
            name='conf_type',
            field=models.CharField(choices=[('international', '\u041c\u0435\u0436\u0434\u0443\u043d\u0430\u0440\u043e\u0434\u043d\u0430\u044f'), ('national', '\u0420\u043e\u0441\u0441\u0438\u0439\u0441\u043a\u0430\u044f')], default='national', max_length=25, verbose_name='\u041a\u043b\u0430\u0441\u0441\u0438\u0444\u0438\u043a\u0430\u0446\u0438\u044f'),
        ),
        migrations.AddField(
            model_name='journal',
            name='date_start',
            field=models.DateTimeField(blank=True, help_text='\u041d\u0430\u0447\u0430\u043b\u043e \u043a\u043e\u043d\u0444\u0435\u0440\u0435\u043d\u0446\u0438\u0438', null=True, verbose_name='\u0414\u0430\u0442\u0430 \u0438 \u0432\u0440\u0435\u043c\u044f, \u043d\u0430\u0447\u0430\u043b\u043e'),
        ),
        migrations.AddField(
            model_name='journal',
            name='date_stop',
            field=models.DateTimeField(blank=True, help_text='\u041a\u043e\u043d\u0435\u0446 \u043a\u043e\u043d\u0444\u0435\u0440\u0435\u043d\u0446\u0438\u0438', null=True, verbose_name='\u0414\u0430\u0442\u0430 \u0438 \u0432\u0440\u0435\u043c\u044f, \u043a\u043e\u043d\u0435\u0446'),
        ),
        migrations.AddField(
            model_name='journal',
            name='organizer',
            field=models.CharField(blank=True, max_length=550, verbose_name='\u041e\u0440\u0433\u0430\u043d\u0438\u0437\u0430\u0442\u043e\u0440'),
        ),
        migrations.AddField(
            model_name='journal',
            name='place',
            field=models.CharField(blank=True, help_text='\u041d\u0430\u043f\u0440\u0438\u043c\u0435\u0440: \u0421\u0442\u0440\u0430\u043d\u0430, \u0433\u043e\u0440\u043e\u0434, \u0443\u043d\u0438\u0432\u0435\u0440\u0441\u0438\u0442\u0435\u0442', max_length=255, verbose_name='\u041c\u0435\u0441\u0442\u043e \u043f\u0440\u043e\u0432\u0435\u0434\u0435\u043d\u0438\u044f'),
        ),
        migrations.AddField(
            model_name='journal',
            name='type',
            field=models.CharField(choices=[('journal', '\u0416\u0443\u0440\u043d\u0430\u043b'), ('conference', '\u041a\u043e\u043d\u0444\u0435\u0440\u0435\u043d\u0446\u0438\u044f')], default='journal', max_length=55),
        ),
        migrations.AlterField(
            model_name='journal',
            name='name',
            field=models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0436\u0443\u0440\u043d\u0430\u043b\u0430, \u043a\u043e\u043d\u0444\u0435\u0440\u0435\u043d\u0446\u0438\u0438'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0436\u0443\u0440\u043d\u0430\u043b\u0430, \u043a\u043e\u043d\u0444\u0435\u0440\u0435\u043d\u0446\u0438\u0438'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0436\u0443\u0440\u043d\u0430\u043b\u0430, \u043a\u043e\u043d\u0444\u0435\u0440\u0435\u043d\u0446\u0438\u0438'),
        ),
    ]
