# Generated by Django 2.0.12 on 2021-10-20 17:23

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0020_publication_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('file', models.FileField(upload_to='uploads/conference/files', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
        migrations.AddField(
            model_name='journal',
            name='conf_link',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ссылка на страницу конференции'),
        ),
        migrations.AddField(
            model_name='journal',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='journal',
            name='short_name',
            field=models.CharField(blank=True, max_length=55, verbose_name='Сокращенное название конференции'),
        ),
        migrations.AddField(
            model_name='files',
            name='conference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='publications.Journal', verbose_name='Журнал/Конференция'),
        ),
    ]
