# Generated by Django 2.0.12 on 2021-10-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0021_auto_20211020_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='conf_checkbox',
            field=models.BooleanField(default=False, verbose_name='Отображение на странице конференций'),
        ),
    ]
