# Generated by Django 2.0.12 on 2021-10-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0023_files_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='filename',
            field=models.CharField(blank=True, help_text='Если поле не заполнено у документа останется прежнее название', max_length=255, verbose_name='Название файла'),
        ),
    ]
