# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-04-16 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0440\u0430\u0441\u0447\u0451\u0442\u0430')),
                ('source_file', models.FileField(max_length=255, upload_to='uploads/igwcoeffs/sources', verbose_name='\u0424\u0430\u0439\u043b \u0441 \u0438\u0441\u0445\u043e\u0434\u043d\u044b\u043c\u0438 \u0434\u0430\u043d\u043d\u044b\u043c\u0438')),
                ('result_file', models.FileField(blank=True, max_length=255, null=True, upload_to='uploads/igwcoeffs/results', verbose_name='\u0424\u0430\u0439\u043b \u0441 \u0440\u0435\u0437\u0443\u043b\u044c\u0442\u0430\u0442\u043e\u043c')),
                ('types', models.PositiveIntegerField(choices=[(0, '\u0420\u0430\u0441\u0447\u0451\u0442 \u0434\u043b\u044f \u043e\u0434\u043d\u043e\u0439 \u0442\u043e\u0447\u043a\u0438'), (1, '\u0420\u0430\u0441\u0447\u0451\u0442 \u0434\u043b\u044f \u0440\u0430\u0437\u0440\u0435\u0437\u0430')], default=0, verbose_name='\u0422\u0438\u043f \u0440\u0430\u0441\u0447\u0451\u0442\u0430')),
                ('mode', models.PositiveIntegerField(choices=[(0, '\u0414\u0432\u0443\u0445 \u043c\u043e\u0434'), (1, '\u041f\u0435\u0440\u0432\u043e\u0439 \u043c\u043e\u0434\u044b'), (2, '\u0412\u0442\u043e\u0440\u043e\u0439 \u043c\u043e\u0434\u044b')], default=1, verbose_name='\u0420\u0430\u0441\u0447\u0451\u0442 \u0434\u043b\u044f')),
                ('email', models.CharField(blank=True, help_text='\u0414\u043b\u044f \u043e\u0442\u043f\u0440\u0430\u0432\u043a\u0438 \u0440\u0435\u0437\u0443\u043b\u044c\u0442\u0430\u0442\u0430 \u0440\u0430\u0441\u0447\u0451\u0442\u0430 \u043d\u0430 \u043f\u043e\u0447\u0442\u0443', max_length=55, verbose_name='Email')),
            ],
            options={
                'verbose_name': '\u0420\u0430\u0441\u0447\u0451\u0442',
                'verbose_name_plural': '\u0420\u0430\u0441\u0447\u0451\u0442\u044b',
            },
        ),
    ]
