# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-06-30 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igwcoeffs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculation',
            name='parse_file_fields',
            field=models.CharField(blank=True, max_length=255, verbose_name='\u0421\u043e\u043e\u0442\u0432\u0435\u0442\u0441\u0442\u0432\u0438\u0435 \u043f\u043e\u043b\u0435\u0439'),
        ),
        migrations.AddField(
            model_name='calculation',
            name='parse_separator',
            field=models.CharField(choices=[(' ', '\u041f\u0440\u043e\u0431\u0435\u043b'), ('/', '/'), (',', ','), (';', ';')], default=' ', max_length=10, verbose_name='\u0420\u0430\u0437\u0434\u0435\u043b\u0438\u0442\u0435\u043b\u044c'),
        ),
        migrations.AddField(
            model_name='calculation',
            name='parse_start_from',
            field=models.PositiveIntegerField(default=0, help_text='\u041d\u043e\u043c\u0435\u0440 \u0441\u0442\u0440\u043e\u043a\u0438', verbose_name='\u0421\u0447\u0438\u0442\u0430\u0442\u044c \u0444\u0430\u0439\u043b \u0441'),
        ),
    ]
