# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-21 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmnad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=b'', verbose_name='\u0424\u0430\u0439\u043b \u0441 \u0442\u0435\u043a\u0442\u043e\u043c \u0441\u0442\u0430\u0442\u044c\u0438'),
        ),
        migrations.AlterField(
            model_name='article',
            name='abstract',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='\u0410\u043d\u043d\u043e\u0442\u0430\u0446\u0438\u044f'),
        ),
    ]
