# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-05 09:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lmnad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='\u0422\u0438\u043f')),
                ('number', models.IntegerField(verbose_name='\u041d\u043e\u043c\u0435\u0440')),
                ('name', models.CharField(max_length=500, verbose_name='\u0422\u0435\u043a\u0441\u0442')),
                ('date_start', models.DateField(verbose_name='\u0414\u0430\u0442\u0430 \u043d\u0430\u0447\u0430\u043b\u0430')),
                ('date_end', models.DateField(verbose_name='\u0414\u0430\u0442\u0430 \u043a\u043e\u043d\u0446\u0430')),
                ('abstract', models.TextField(verbose_name='\u0410\u043d\u043d\u043e\u0442\u0430\u0446\u0438\u044f')),
                ('reference', models.CharField(max_length=500, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 \u043d\u0430 \u0433\u0440\u0430\u043d\u0442')),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='head', to='lmnad.Account', verbose_name='\u0420\u0443\u043a\u043e\u0432\u043e\u0434\u0438\u0442\u0435\u043b\u044c')),
                ('members', models.ManyToManyField(related_name='members', to='lmnad.Account', verbose_name='\u0423\u0447\u0430\u0441\u0442\u043d\u0438\u043a\u0438')),
            ],
            options={
                'verbose_name': '\u0413\u0440\u0430\u043d\u0442',
                'verbose_name_plural': '\u0413\u0440\u0430\u043d\u0442\u044b',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043f\u0440\u043e\u0435\u043a\u0442\u0430 \u043d\u0430 \u0430\u043d\u0433\u043b\u0438\u0439\u0441\u043a\u043e\u043c')),
                ('title', models.CharField(max_length=200, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('text', models.TextField(verbose_name='\u0422\u0435\u043a\u0441\u0442')),
            ],
            options={
                'verbose_name': '\u041f\u0440\u043e\u0435\u043a\u0442',
                'verbose_name_plural': '\u041f\u0440\u043e\u0435\u043a\u0442\u044b',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='is_send_email',
            field=models.BooleanField(choices=[(0, '\u041d\u0435\u0442'), (1, '\u0414\u0430')], default=0, verbose_name='\u0421\u0434\u0435\u043b\u0430\u0442\u044c \u0440\u0430\u0441\u0441\u044b\u043b\u043a\u0443'),
        ),
        migrations.AddField(
            model_name='people',
            name='elibrary',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u041f\u0440\u043e\u0444\u0438\u043b\u044c \u043d\u0430 Elibrary'),
        ),
        migrations.AddField(
            model_name='people',
            name='science_index',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u041d\u0430\u0443\u0447\u043d\u044b\u0439 \u0438\u043d\u0434\u0435\u043a\u0441'),
        ),
        migrations.AddField(
            model_name='protection',
            name='is_send_email',
            field=models.BooleanField(choices=[(0, '\u041d\u0435\u0442'), (1, '\u0414\u0430')], default=0, verbose_name='\u0421\u0434\u0435\u043b\u0430\u0442\u044c \u0440\u0430\u0441\u0441\u044b\u043b\u043a\u0443'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='is_send_email',
            field=models.BooleanField(choices=[(0, '\u041d\u0435\u0442'), (1, '\u0414\u0430')], default=0, verbose_name='\u0421\u0434\u0435\u043b\u0430\u0442\u044c \u0440\u0430\u0441\u0441\u044b\u043b\u043a\u0443'),
        ),
        migrations.AlterField(
            model_name='people',
            name='account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lmnad.Account', verbose_name='\u0410\u043a\u043a\u0430\u0443\u043d\u0442 \u0441\u043e\u0442\u0440\u0443\u0434\u043d\u0438\u043a\u0430'),
        ),
    ]
