# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-21 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmnad', '0002_auto_20161221_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='articles/', verbose_name='\u0424\u0430\u0439\u043b \u0441 \u0442\u0435\u043a\u0442\u043e\u043c \u0441\u0442\u0430\u0442\u044c\u0438'),
        ),
    ]
