# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-12 22:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lmnad', '0003_auto_20161221_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lmnad.Account'),
        )
    ]
