# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-05 12:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmnad', '0004_auto_20170205_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='elibrary',
        ),
    ]
