# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-12 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmnad', '0004_auto_20170113_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_subscribe',
            field=models.BooleanField(default=True, verbose_name='\u041f\u043e\u0434\u043f\u0438\u0441\u043a\u0430 \u043d\u0430 email \u043e\u043f\u043e\u0432\u0435\u0449\u0435\u043d\u0438\u044f'),
        ),
    ]
