# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-12 22:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmnad', '0005_auto_20170113_0110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='page',
            new_name='text',
        ),
    ]
