# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-06 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmnad', '0005_remove_people_elibrary'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='short_text',
            field=models.TextField(blank=True, null=True, verbose_name='\u041a\u043e\u0440\u043e\u0442\u043a\u043e\u0435 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
        ),
    ]
