# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-07 17:06
from __future__ import unicode_literals

from django.db import migrations
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lmnad', '0007_people_order_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=200, null=True, verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u044f'),
        ),
        migrations.AddField(
            model_name='project',
            name='image_initialdir',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=200, null=True, verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u044f (\u0414\u0438\u0440\u0435\u043a\u0442\u043e\u0440\u0438\u044f)'),
        ),
    ]
