# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-07 17:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmnad', '0008_auto_20170207_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image_initialdir',
        ),
    ]
