# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-07 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmnad', '0007_people_order_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': '\u041f\u0435\u0440\u0441\u043e\u043d\u0430\u043b\u044c\u043d\u0430\u044f \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0430', 'verbose_name_plural': '\u041f\u0435\u0440\u0441\u043e\u043d\u0430\u043b\u044c\u043d\u044b\u0435 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b'},
        ),
        migrations.AlterField(
            model_name='account',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/users/cv/', verbose_name='\u0424\u0430\u0439\u043b CV'),
        ),
        migrations.AlterField(
            model_name='article',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/articles/', verbose_name='\u0424\u0430\u0439\u043b \u0441 \u0442\u0435\u043a\u0442\u043e\u043c \u0441\u0442\u0430\u0442\u044c\u0438'),
        ),
    ]
