# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-30 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmnad', '0011_auto_20170327_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='order_by',
            field=models.PositiveIntegerField(default=0, verbose_name='\u0421\u043e\u0440\u0442\u0438\u0440\u043e\u0432\u0430\u0442\u044c'),
        ),
    ]
