# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-30 05:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmnad', '0012_grant_order_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grant',
            name='order_by',
        ),
    ]
