# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-30 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmnad', '0014_auto_20170330_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='is_send_email',
            field=models.BooleanField(default=False, verbose_name='\u0421\u0434\u0435\u043b\u0430\u0442\u044c \u0440\u0430\u0441\u0441\u044b\u043b\u043a\u0443'),
        ),
        migrations.AlterField(
            model_name='people',
            name='status',
            field=models.BooleanField(default=True, verbose_name='\u0420\u0430\u0431\u043e\u0442\u0430\u0435\u0442'),
        ),
        migrations.AlterField(
            model_name='protection',
            name='is_send_email',
            field=models.BooleanField(default=False, verbose_name='\u0421\u0434\u0435\u043b\u0430\u0442\u044c \u0440\u0430\u0441\u0441\u044b\u043b\u043a\u0443'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='is_send_email',
            field=models.BooleanField(default=False, verbose_name='\u0421\u0434\u0435\u043b\u0430\u0442\u044c \u0440\u0430\u0441\u0441\u044b\u043b\u043a\u0443'),
        ),
    ]
