# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-30 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmnad', '0015_auto_20170330_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='full_text',
            field=models.TextField(blank=True, verbose_name='\u041f\u043e\u043b\u043d\u044b\u0439 \u0442\u0435\u043a\u0441\u0442, \u043e\u0442\u0447\u0451\u0442'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='full_text',
            field=models.TextField(blank=True, verbose_name='\u041f\u043e\u043b\u043d\u044b\u0439 \u0442\u0435\u043a\u0441\u0442, \u043e\u0442\u0447\u0451\u0442'),
        ),
        migrations.AlterField(
            model_name='event',
            name='text',
            field=models.TextField(verbose_name='\u041a\u0440\u0430\u0442\u043a\u043e\u0435 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='text',
            field=models.TextField(verbose_name='\u041a\u0440\u0430\u0442\u043a\u043e\u0435 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
        ),
    ]
