# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-26 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmnad', '0017_auto_20170426_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protection',
            name='date',
            field=models.DateField(blank=True, verbose_name='\u0414\u0430\u0442\u0430'),
        ),
    ]
