# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-29 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmnad', '0021_auto_20170429_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='text_en',
            field=models.TextField(blank=True, null=True, verbose_name='\u041f\u0435\u0440\u0441\u043e\u043d\u0430\u043b\u044c\u043d\u0430\u044f \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0430'),
        ),
        migrations.AddField(
            model_name='account',
            name='text_ru',
            field=models.TextField(blank=True, null=True, verbose_name='\u041f\u0435\u0440\u0441\u043e\u043d\u0430\u043b\u044c\u043d\u0430\u044f \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0430'),
        ),
        migrations.AddField(
            model_name='article',
            name='abstract_en',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='\u0410\u043d\u043d\u043e\u0442\u0430\u0446\u0438\u044f'),
        ),
        migrations.AddField(
            model_name='article',
            name='abstract_ru',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='\u0410\u043d\u043d\u043e\u0442\u0430\u0446\u0438\u044f'),
        ),
        migrations.AddField(
            model_name='article',
            name='authors_en',
            field=models.CharField(max_length=200, null=True, verbose_name='\u0410\u0432\u0442\u043e\u0440\u044b'),
        ),
        migrations.AddField(
            model_name='article',
            name='authors_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='\u0410\u0432\u0442\u043e\u0440\u044b'),
        ),
        migrations.AddField(
            model_name='article',
            name='source_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u0416\u0443\u0440\u043d\u0430\u043b, \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b'),
        ),
        migrations.AddField(
            model_name='article',
            name='source_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u0416\u0443\u0440\u043d\u0430\u043b, \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435'),
        ),
        migrations.AddField(
            model_name='event',
            name='full_text_en',
            field=models.TextField(blank=True, null=True, verbose_name='\u041f\u043e\u043b\u043d\u044b\u0439 \u0442\u0435\u043a\u0441\u0442, \u043e\u0442\u0447\u0451\u0442'),
        ),
        migrations.AddField(
            model_name='event',
            name='full_text_ru',
            field=models.TextField(blank=True, null=True, verbose_name='\u041f\u043e\u043b\u043d\u044b\u0439 \u0442\u0435\u043a\u0441\u0442, \u043e\u0442\u0447\u0451\u0442'),
        ),
        migrations.AddField(
            model_name='event',
            name='text_en',
            field=models.TextField(null=True, verbose_name='\u041a\u0440\u0430\u0442\u043a\u043e\u0435 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
        ),
        migrations.AddField(
            model_name='event',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='\u041a\u0440\u0430\u0442\u043a\u043e\u0435 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
        ),
        migrations.AddField(
            model_name='event',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
        ),
        migrations.AddField(
            model_name='event',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
        ),
        migrations.AddField(
            model_name='grant',
            name='abstract_en',
            field=models.TextField(blank=True, null=True, verbose_name='\u0410\u043d\u043d\u043e\u0442\u0430\u0446\u0438\u044f'),
        ),
        migrations.AddField(
            model_name='grant',
            name='abstract_ru',
            field=models.TextField(blank=True, null=True, verbose_name='\u0410\u043d\u043d\u043e\u0442\u0430\u0446\u0438\u044f'),
        ),
        migrations.AddField(
            model_name='grant',
            name='name_en',
            field=models.CharField(max_length=500, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442'),
        ),
        migrations.AddField(
            model_name='grant',
            name='name_ru',
            field=models.CharField(max_length=500, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442'),
        ),
        migrations.AddField(
            model_name='grant',
            name='type_en',
            field=models.CharField(max_length=50, null=True, verbose_name='\u0422\u0438\u043f'),
        ),
        migrations.AddField(
            model_name='grant',
            name='type_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='\u0422\u0438\u043f'),
        ),
        migrations.AddField(
            model_name='page',
            name='text_en',
            field=models.TextField(null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442'),
        ),
        migrations.AddField(
            model_name='page',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442'),
        ),
        migrations.AddField(
            model_name='page',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
        ),
        migrations.AddField(
            model_name='page',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
        ),
        migrations.AddField(
            model_name='people',
            name='degree_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u0421\u0442\u0435\u043f\u0435\u043d\u044c'),
        ),
        migrations.AddField(
            model_name='people',
            name='degree_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u0421\u0442\u0435\u043f\u0435\u043d\u044c'),
        ),
        migrations.AddField(
            model_name='people',
            name='fullname_en',
            field=models.CharField(max_length=200, null=True, verbose_name='\u0424\u0418\u041e'),
        ),
        migrations.AddField(
            model_name='people',
            name='fullname_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='\u0424\u0418\u041e'),
        ),
        migrations.AddField(
            model_name='people',
            name='position_en',
            field=models.CharField(max_length=50, null=True, verbose_name='\u0414\u043e\u043b\u0436\u043d\u043e\u0441\u0442\u044c'),
        ),
        migrations.AddField(
            model_name='people',
            name='position_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='\u0414\u043e\u043b\u0436\u043d\u043e\u0441\u0442\u044c'),
        ),
        migrations.AddField(
            model_name='people',
            name='rank_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u0423\u0447\u0451\u043d\u043e\u0435 \u0437\u0432\u0430\u043d\u0438\u0435'),
        ),
        migrations.AddField(
            model_name='people',
            name='rank_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u0423\u0447\u0451\u043d\u043e\u0435 \u0437\u0432\u0430\u043d\u0438\u0435'),
        ),
        migrations.AddField(
            model_name='protection',
            name='author_en',
            field=models.CharField(max_length=100, null=True, verbose_name='\u0410\u0432\u0442\u043e\u0440'),
        ),
        migrations.AddField(
            model_name='protection',
            name='author_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='\u0410\u0432\u0442\u043e\u0440'),
        ),
        migrations.AddField(
            model_name='protection',
            name='message_en',
            field=models.TextField(null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442'),
        ),
        migrations.AddField(
            model_name='protection',
            name='message_ru',
            field=models.TextField(null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442'),
        ),
        migrations.AddField(
            model_name='protection',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0440\u0430\u0431\u043e\u0442\u044b'),
        ),
        migrations.AddField(
            model_name='protection',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0440\u0430\u0431\u043e\u0442\u044b'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='full_text_en',
            field=models.TextField(blank=True, null=True, verbose_name='\u041f\u043e\u043b\u043d\u044b\u0439 \u0442\u0435\u043a\u0441\u0442, \u043e\u0442\u0447\u0451\u0442'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='full_text_ru',
            field=models.TextField(blank=True, null=True, verbose_name='\u041f\u043e\u043b\u043d\u044b\u0439 \u0442\u0435\u043a\u0441\u0442, \u043e\u0442\u0447\u0451\u0442'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='text_en',
            field=models.TextField(null=True, verbose_name='\u041a\u0440\u0430\u0442\u043a\u043e\u0435 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='\u041a\u0440\u0430\u0442\u043a\u043e\u0435 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
        ),
    ]
