# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-06-14 14:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmnad', '0024_project_is_only_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '(Old) \u0421\u0442\u0430\u0442\u044c\u044f', 'verbose_name_plural': '(Old) \u0421\u0442\u0430\u0442\u044c\u0438'},
        ),
    ]
