# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-09-03 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmnad', '0029_event_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='wiki',
            name='link',
            field=models.CharField(blank=True, max_length=255, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430'),
        ),
        migrations.AlterField(
            model_name='wiki',
            name='text',
            field=models.TextField(max_length=5000, verbose_name='\u0422\u0435\u043a\u0441\u0442'),
        ),
    ]
