# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-09-18 13:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lmnad', '0030_auto_20180903_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='account',
            field=models.OneToOneField(blank=True, help_text='\u0415\u0441\u043b\u0438 \u0435\u0441\u0442\u044c', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='people', to='lmnad.Account', verbose_name='\u0410\u043a\u043a\u0430\u0443\u043d\u0442 \u0441\u043e\u0442\u0440\u0443\u0434\u043d\u0438\u043a\u0430'),
        ),
    ]
