# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-09-20 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmnad', '0031_auto_20180918_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='cv_file',
            field=models.FileField(blank=True, help_text='\u041f\u0440\u0438\u043a\u0440\u0435\u043f\u0438\u0442\u044c \u0441\u0443\u0449\u0435\u0441\u0442\u0432\u0443\u044e\u0449\u0435\u0435 CV', null=True, upload_to='uploads/users/cv/', verbose_name='\u0424\u0430\u0439\u043b CV'),
        ),
        migrations.AlterField(
            model_name='account',
            name='text',
            field=models.TextField(blank=True, help_text='\u0412 \u043f\u0440\u043e\u0438\u0437\u0432\u043e\u043b\u044c\u043d\u043e\u0439 \u0444\u043e\u0440\u043c\u0435', null=True, verbose_name='\u041f\u0435\u0440\u0441\u043e\u043d\u0430\u043b\u044c\u043d\u0430\u044f \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0430'),
        ),
        migrations.AlterField(
            model_name='account',
            name='text_en',
            field=models.TextField(blank=True, help_text='\u0412 \u043f\u0440\u043e\u0438\u0437\u0432\u043e\u043b\u044c\u043d\u043e\u0439 \u0444\u043e\u0440\u043c\u0435', null=True, verbose_name='\u041f\u0435\u0440\u0441\u043e\u043d\u0430\u043b\u044c\u043d\u0430\u044f \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0430'),
        ),
        migrations.AlterField(
            model_name='account',
            name='text_ru',
            field=models.TextField(blank=True, help_text='\u0412 \u043f\u0440\u043e\u0438\u0437\u0432\u043e\u043b\u044c\u043d\u043e\u0439 \u0444\u043e\u0440\u043c\u0435', null=True, verbose_name='\u041f\u0435\u0440\u0441\u043e\u043d\u0430\u043b\u044c\u043d\u0430\u044f \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0430'),
        ),
    ]
