# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-09-29 03:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lmnad', '0032_auto_20180920_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lmnad.Images', verbose_name='\u0424\u043e\u0442\u043e'),
        ),
    ]
