# Generated by Django 2.0 on 2018-10-19 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lmnad', '0033_account_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lmnad.Images', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='people',
            name='account',
            field=models.OneToOneField(blank=True, help_text='Если есть', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people', to='lmnad.Account', verbose_name='Аккаунт сотрудника'),
        ),
    ]
