# Generated by Django 2.0.10 on 2019-05-08 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmnad', '0034_auto_20181019_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, max_length=500, null=True, upload_to='uploads/lmnad/files', verbose_name='Файл')),
            ],
            options={
                'verbose_name_plural': 'Файлы',
                'verbose_name': 'Файл',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='images',
            field=models.ManyToManyField(blank=True, help_text='Для отображения на странице проекта', to='lmnad.Images', verbose_name='Изображения'),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_text',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_text_en',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_text_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='project',
            name='documents',
            field=models.ManyToManyField(blank=True, help_text='Для доступа на странице проекта', to='lmnad.File', verbose_name='Документы'),
        ),
    ]
