# Generated by Django 2.0.10 on 2019-11-09 13:46

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lmnad', '0035_auto_20190508_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsefulLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=255, verbose_name='Название ссылки, заголовок')),
                ('link', models.URLField(help_text='https:/ya.ru', verbose_name='URL Ссылки')),
            ],
            options={
                'verbose_name_plural': 'Полезные ссылки',
                'verbose_name': 'Полезная ссылка',
            },
        ),
    ]
