# Generated by Django 2.0.10 on 2019-11-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmnad', '0036_usefullink'),
    ]

    operations = [
        migrations.AddField(
            model_name='usefullink',
            name='order_by',
            field=models.PositiveIntegerField(default=0, verbose_name='Сортировать'),
        ),
    ]
