# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-04-18 11:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tank', '0002_experiment_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='src',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='images',
            old_name='src',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='src',
            new_name='file',
        ),
    ]
