# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-04-24 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tank', '0003_auto_20180418_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='is_schema',
            field=models.BooleanField(default=False, help_text='\u0414\u0430, \u043d\u0435\u0442', verbose_name='C\u0445\u0435\u043c\u0430 \u044d\u043a\u0441\u043f\u0435\u0440\u0438\u043c\u0435\u043d\u0442\u0430'),
        ),
    ]
